
puts "DIGITE O VALOR DE RAIO DA CIRCUNFERENCIA  : "
RAIO = gets.chomp.to_f
puts ""


#### CALCULO DE AREA DE CIRCUNFERENCIA #####
AREA = (2 * 3.14159265 * RAIO)

puts " VALOR DA AREA DE CIRCUNFERENCIA #{AREA}"
